class_name GConstants

const TCP_MESSAGE_TYPE_MOVE_CURSOR = 0
const TCP_MESSAGE_TYPE_PRESS_CURSOR_BUTTON = 1
const TCP_MESSAGE_TYPE_VIRTUAL_KEY = 2
const TCP_MESSAGE_TYPE_CURSOR_SPEED = 3
const TCP_MESSAGE_TYPE_POWER_ACTION = 4

const POWER_OPTION_NONE: int = 0
const POWER_OPTION_SLEEP: int = 1
const POWER_OPTION_SHUTDOWN: int = 2
